### ISSUE TITLE
只能打印一行

### ISSUE THREAD

**Issue by Mrlie** [huanent/Huanent.Printer#1]
我测试了一下，只能打印一行，\r\n换行符打印不出来第二行

            string printName = "xp-58";
            var print = PrinterFactory.GetPrinter(printName, PrintWidth.Print58mm);
            print.Print(new PrintUnit[] {
                new PrintUnit{
                    Alignment =StringAlignment.Center,
                    Content ="---欢迎光临----\r\n西瓜 20KG 120元",
                    UnitWidth=100,
                    Y =10,
                    Font =new Font("黑体",12)
                }
            });

**Comment by huanent** [comment]
可以考虑使用两个打印单元，但设置不同的y值来模拟换行的效果

**Comment by huanent** [comment]
已经发布2.0版本，此版本完美解决了换行问题 @Mrlie

**Comment by Mrlie** [comment]
非常感谢你还能更新！！！

**Comment by huanent** [comment]
不客气，有问题可以再提Issues哈
