### ISSUE TITLE
打印出现丢失二维码的情况吗？

### ISSUE THREAD

**Issue by longas1232** [huanent/Huanent.Printer#7]
您好 请问您出现过丢失二维码的现象吗？

**Comment by huanent** [comment]
要么都有，要么都没有，应该不会出现少了部分的现象，看下是不是纸张长度设置不够长

**Comment by longas1232** [comment]
不是那种 都有都没有的情况 我看您的代码里是没有对 Graphics资源做Dispose的 但是我们做了Dispose 有的时候其他元素 字体啊 等等正常打印 但是就是二维码丢失了 很奇怪

**Comment by longas1232** [comment]
而且直接发送给 打印机 和 后台打印好像结果也不尽相同 不知道您这方面有经验嘛

**Comment by huanent** [comment]
Graphics资源做Dispose应该是不需要的，打印事件结束后释放PrintDocument时会在内部调用释放。
发送给 打印机 和 后台打印结果不同，因为打印机品牌型号这些各尽不同，所以无法回答

**Comment by huanent** [comment]
资源释放问题可以参见msdn https://docs.microsoft.com/zh-cn/dotnet/api/system.drawing.printing.printdocument?view=netframework-4.8

**Comment by longas1232** [comment]
十分感谢 我尝试不在打印过程中 释放g.graphics资源 而是在Print()方法之后释放 printDocument.dispose方法 但是我观察内存是不断的上涨的 不知道您遇到过这种情况吗？

**Comment by huanent** [comment]
get到print对象后要存成单例复用，2.0没有Print()方法，如果不是用2.0，需要迁移到2.0版本。2.0在finish方法后会释放掉printDocument对象，相应的graphics也会释放
